using System.Net;
using System.Text;

namespace DriveVisualizer.Core.Snapshots;

/// <summary>
/// Renders a self-contained HTML report for a scan snapshot, optionally with a
/// comparison against an older baseline snapshot (top growers/shrinkers).
/// Print the page to get a PDF — no external assets, print CSS included.
/// </summary>
public static class ReportGenerator
{
    // Category hues per surface: light-surface steps and the dark-surface steps
    // the app's treemap legend uses (same validated categorical palette).
    private static readonly string[] CategoryHexLight =
        ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948", "#6b6b68"];
    private static readonly string[] CategoryHexDark =
        ["#3987e5", "#d95926", "#199e70", "#c98500", "#d55181", "#008300", "#9085e9", "#e66767", "#6b6b68"];

    public static string BuildHtml(ScanSnapshot current, ScanSnapshot? baseline = null, string? baselineSource = null)
    {
        var sb = new StringBuilder(64 * 1024);
        string title = $"DriveVisualizer report — {WebUtility.HtmlEncode(current.Target)}";

        var catVarsLight = string.Join(" ", CategoryHexLight.Select((h, i) => $"--cat{i}: {h};"));
        var catVarsDark = string.Join(" ", CategoryHexDark.Select((h, i) => $"--cat{i}: {h};"));

        sb.Append($$"""
            <!doctype html>
            <html lang="en"><head><meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{{title}}</title>
            <style>
              :root {
                color-scheme: light dark;
                --page: #f9f9f7; --surface: #fcfcfb; --ink: #0b0b0b; --ink2: #52514e;
                --grid: #e1e0d9; --border: rgba(11,11,11,.10); --track: #e1e0d9;
                --pos: #b91c1c; --neg: #006300;
                {{catVarsLight}}
              }
              @media (prefers-color-scheme: dark) {
                :root {
                  --page: #0d0d0d; --surface: #1a1a19; --ink: #ffffff; --ink2: #c3c2b7;
                  --grid: #2c2c2a; --border: rgba(255,255,255,.10); --track: #383835;
                  --pos: #e66767; --neg: #0ca30c;
                  {{catVarsDark}}
                }
              }
              body { font: 14px/1.5 system-ui, "Segoe UI", sans-serif; color: var(--ink); background: var(--page); margin: 0; }
              .page { max-width: 960px; margin: 0 auto; padding: 32px 24px 64px; }
              h1 { font-size: 22px; margin: 0 0 4px; }
              h2 { font-size: 16px; margin: 32px 0 8px; }
              .muted { color: var(--ink2); }
              .tiles { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 16px; }
              .tile { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 12px 16px; min-width: 150px; }
              .tile .v { font-size: 22px; font-weight: 600; }
              .tile .d { font-size: 12px; }
              table { border-collapse: collapse; width: 100%; background: var(--surface); border: 1px solid var(--border); border-radius: 8px; }
              th, td { text-align: left; padding: 6px 10px; border-top: 1px solid var(--grid); font-variant-numeric: tabular-nums; }
              thead th { border-top: none; font-size: 12px; color: var(--ink2); }
              td.num, th.num { text-align: right; white-space: nowrap; }
              .swatch { display: inline-block; width: 10px; height: 10px; border-radius: 2px; margin-right: 6px; vertical-align: baseline; }
              .bar { background: var(--track); border-radius: 3px; height: 8px; min-width: 120px; }
              .bar > i { display: block; height: 8px; border-radius: 3px; }
              .pos { color: var(--pos); } .neg { color: var(--neg); }
              .path { word-break: break-all; }
              @media print { body { background: #fff; color: #0b0b0b; } .page { padding: 0; } }
            </style></head><body><div class="page">
            """);

        sb.Append($"<h1>DriveVisualizer report</h1>");
        sb.Append($"<div class=\"muted\">{WebUtility.HtmlEncode(current.Target)} — scanned {current.TimestampUtc:yyyy-MM-dd HH:mm} UTC");
        if (baseline is not null)
            sb.Append($" · compared with {WebUtility.HtmlEncode(baseline.Target)} from {baseline.TimestampUtc:yyyy-MM-dd HH:mm} UTC");
        sb.Append("</div>");
        if (baseline is not null && baselineSource is not null)
            sb.Append($"<div class=\"muted\" style=\"font-size:12px\">Baseline: {WebUtility.HtmlEncode(baselineSource)}</div>");

        AppendSummaryTiles(sb, current, baseline);
        AppendCategories(sb, current, baseline);
        if (baseline is not null)
            AppendComparison(sb, current, baseline);
        AppendTopDirectories(sb, current);
        AppendTopFiles(sb, current);

        sb.Append("<p class=\"muted\" style=\"margin-top:32px;font-size:12px\">Generated by DriveVisualizer. Use your browser's Print → Save as PDF for a PDF copy.</p>");
        sb.Append("</div></body></html>");
        return sb.ToString();
    }

    private static void AppendSummaryTiles(StringBuilder sb, ScanSnapshot current, ScanSnapshot? baseline)
    {
        sb.Append("<div class=\"tiles\">");
        AppendTile(sb, "Total size", ByteFormatter.Format(current.TotalAllocated),
            baseline is null ? null : current.TotalAllocated - baseline.TotalAllocated, bytes: true);
        AppendTile(sb, "Files", current.TotalFiles.ToString("N0"),
            baseline is null ? null : current.TotalFiles - baseline.TotalFiles, bytes: false);
        AppendTile(sb, "Folders", current.TotalDirectories.ToString("N0"),
            baseline is null ? null : current.TotalDirectories - baseline.TotalDirectories, bytes: false);
        sb.Append("</div>");
    }

    private static void AppendTile(StringBuilder sb, string label, string value, long? delta, bool bytes)
    {
        sb.Append($"<div class=\"tile\"><div class=\"muted\" style=\"font-size:12px\">{label}</div><div class=\"v\">{value}</div>");
        if (delta is { } d && d != 0)
        {
            string cls = d > 0 ? "pos" : "neg";
            string text = bytes ? ByteFormatter.Format(Math.Abs(d)) : Math.Abs(d).ToString("N0");
            sb.Append($"<div class=\"d {cls}\">{(d > 0 ? "▲ +" : "▼ −")}{text} since baseline</div>");
        }
        sb.Append("</div>");
    }

    private static void AppendCategories(StringBuilder sb, ScanSnapshot current, ScanSnapshot? baseline)
    {
        sb.Append("<h2>By file type</h2><table><thead><tr><th>Category</th><th>Share</th><th class=\"num\">Size</th>");
        if (baseline is not null)
            sb.Append("<th class=\"num\">Change</th>");
        sb.Append("</tr></thead><tbody>");

        for (int i = 0; i < current.CategoryBytes.Length && i < FileClassification.CategoryCount; i++)
        {
            long size = current.CategoryBytes[i];
            if (size <= 0)
                continue;
            double pct = current.TotalAllocated > 0 ? 100.0 * size / current.TotalAllocated : 0;
            string colorVar = $"var(--cat{Math.Min(i, CategoryHexDark.Length - 1)})";
            sb.Append($"<tr><td><span class=\"swatch\" style=\"background:{colorVar}\"></span>{WebUtility.HtmlEncode(FileClassification.DisplayNames[i])}</td>");
            sb.Append($"<td><div class=\"bar\"><i style=\"width:{pct:F1}%;background:{colorVar}\"></i></div></td>");
            sb.Append($"<td class=\"num\">{ByteFormatter.Format(size)} ({pct:F1}%)</td>");
            if (baseline is not null)
            {
                long baseSize = i < baseline.CategoryBytes.Length ? baseline.CategoryBytes[i] : 0;
                long delta = size - baseSize;
                string cls = delta > 0 ? "pos" : delta < 0 ? "neg" : "";
                sb.Append($"<td class=\"num {cls}\">{(delta == 0 ? "—" : (delta > 0 ? "+" : "−") + ByteFormatter.Format(Math.Abs(delta)))}</td>");
            }
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table>");
    }

    private static void AppendTopDirectories(StringBuilder sb, ScanSnapshot current)
    {
        var paths = current.BuildDirectoryPaths();
        var top = current.Directories
            .Select((d, i) => (Dir: d, Path: paths[i]))
            .Where(x => x.Dir.ParentIndex >= 0)
            .OrderByDescending(x => x.Dir.AllocatedSize)
            .Take(20);

        sb.Append("<h2>Largest folders</h2><table><thead><tr><th>Folder</th><th class=\"num\">Size</th><th class=\"num\">Files</th></tr></thead><tbody>");
        foreach (var (dir, path) in top)
            sb.Append($"<tr><td class=\"path\">{WebUtility.HtmlEncode(path)}</td><td class=\"num\">{ByteFormatter.Format(dir.AllocatedSize)}</td><td class=\"num\">{dir.FileCount:N0}</td></tr>");
        sb.Append("</tbody></table>");
    }

    private static void AppendTopFiles(StringBuilder sb, ScanSnapshot current)
    {
        sb.Append("<h2>Largest files</h2><table><thead><tr><th>File</th><th class=\"num\">Size</th></tr></thead><tbody>");
        foreach (var file in current.TopFiles.Take(50))
            sb.Append($"<tr><td class=\"path\">{WebUtility.HtmlEncode(file.Path)}</td><td class=\"num\">{ByteFormatter.Format(file.AllocatedSize)}</td></tr>");
        sb.Append("</tbody></table>");
    }

    private static void AppendComparison(StringBuilder sb, ScanSnapshot current, ScanSnapshot baseline)
    {
        var currentPaths = current.BuildDirectoryPaths();
        var baselinePaths = baseline.BuildDirectoryPaths();

        var baselineByPath = new Dictionary<string, long>(baseline.Directories.Count, StringComparer.OrdinalIgnoreCase);
        for (int i = 0; i < baseline.Directories.Count; i++)
            baselineByPath[baselinePaths[i]] = baseline.Directories[i].AllocatedSize;

        var deltas = new List<(string Path, long Then, long Delta, long Now)>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        for (int i = 0; i < current.Directories.Count; i++)
        {
            string path = currentPaths[i];
            seen.Add(path);
            long now = current.Directories[i].AllocatedSize;
            long before = baselineByPath.TryGetValue(path, out long b) ? b : 0;
            if (now != before)
                deltas.Add((path, before, now - before, now));
        }
        for (int i = 0; i < baseline.Directories.Count; i++)
            if (!seen.Contains(baselinePaths[i]) && baseline.Directories[i].AllocatedSize > 0)
                deltas.Add((baselinePaths[i] + "  (removed)", baseline.Directories[i].AllocatedSize, -baseline.Directories[i].AllocatedSize, 0));

        AppendDeltaTable(sb, "What grew", deltas.Where(d => d.Delta > 0).OrderByDescending(d => d.Delta).Take(20), positive: true);
        AppendDeltaTable(sb, "What shrank", deltas.Where(d => d.Delta < 0).OrderBy(d => d.Delta).Take(20), positive: false);

        var fileMovers = HistoryChart.ComputeFileMovers(baseline, current, 20);
        if (fileMovers.Count > 0)
        {
            sb.Append("<h2>Largest file changes</h2><table><tbody>");
            foreach (var (path, delta) in fileMovers)
                sb.Append($"<tr><td style=\"text-align:left\" class=\"path\">{WebUtility.HtmlEncode(path)}</td>" +
                          $"<td class=\"num {(delta > 0 ? "pos" : "neg")}\">{(delta > 0 ? "+" : "−")}{ByteFormatter.Format(Math.Abs(delta))}</td></tr>");
            sb.Append("</tbody></table>");
            sb.Append("<div class=\"muted\" style=\"font-size:12px;margin-top:4px\">File changes are tracked among each snapshot's largest files; a file listed as removed may also have shrunk out of that set.</div>");
        }
    }

    private static void AppendDeltaTable(StringBuilder sb, string title, IEnumerable<(string Path, long Then, long Delta, long Now)> rows, bool positive)
    {
        sb.Append($"<h2>{title}</h2><table><thead><tr><th>Folder</th><th class=\"num\">Then</th><th class=\"num\">Change</th><th class=\"num\">Now</th></tr></thead><tbody>");
        bool any = false;
        foreach (var (path, then, delta, now) in rows)
        {
            any = true;
            string cls = positive ? "pos" : "neg";
            sb.Append($"<tr><td class=\"path\">{WebUtility.HtmlEncode(path)}</td>" +
                      $"<td class=\"num\">{ByteFormatter.Format(then)}</td>" +
                      $"<td class=\"num {cls}\">{(positive ? "+" : "−")}{ByteFormatter.Format(Math.Abs(delta))}</td>" +
                      $"<td class=\"num\">{ByteFormatter.Format(now)}</td></tr>");
        }
        if (!any)
            sb.Append("<tr><td colspan=\"4\" class=\"muted\">No changes</td></tr>");
        sb.Append("</tbody></table>");
    }
}
